# Generated by Django 4.1 on 2024-03-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='movie.country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='movie.country'),
        ),
    ]
