# Generated by Django 4.1 on 2024-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='director_photos'),
        ),
    ]
