# Generated by Django 4.1 on 2024-03-09 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0003_alter_director_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["first_name"]},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"ordering": ["first_name"], "verbose_name_plural": "Directors"},
        ),
    ]
